### PR TITLE
Adding style

### PR DESCRIPTION
**Pull request by Padmnabhc**
Add  Hello Microverse
Add Html and Css

### CODE REVIEW

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @Padmnabhc , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Aspects to improve ♻️

- [ ] Please make sure all your linters are passing (green) before submitting a Pull Request.
- [ ] Kindly create a title and a descriptive summary for your Pull Request.
- [ ] Kindly customize your README.md file for your project. Use the title of this project, create a description for it, use your social links and data for the author section, etc.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Padmnabhc** [comment]
@leonardodiasb 
I need your help as I am stuck in my project. can you please help.

**Review by algerina — APPROVED** [review]
Hi @Padmnabhc , 
Good job so far!

May I highlight the following:

- The repo looks good.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSE
 


 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by Padmnabhc** [comment]
Hello Microverse project successfully done.

**Pull request merged**
